#include "wifi_known_networks_core.h"
#include <limits.h>
#include <string.h>

#define ENTRY_FLAG_OCCUPIED 0x01U
#define ENTRY_FLAG_AUTO 0x02U
#define ENTRY_FLAG_BSSID 0x04U
#define WIRE_ENTRY_SIZE (1U+1U+1U+1U+1U+6U+4U+33U+65U)
#define WIRE_HEADER_SIZE 12U
#define WIRE_CRC_SIZE 4U
#define WIRE_TOTAL_SIZE (WIRE_HEADER_SIZE + WIFI_KNOWN_NETWORK_MAX*WIRE_ENTRY_SIZE + WIRE_CRC_SIZE)

static size_t bounded(const char *s,size_t max){size_t n=0;if(!s)return max+1U;while(n<=max&&s[n])++n;return n;}
static bool mac_valid(const uint8_t m[6]){if(!m||(m[0]&1U))return false;uint8_t a=0;for(unsigned i=0;i<6;i++)a|=m[i];return a!=0;}
static void put32(uint8_t*p,uint32_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8);p[2]=(uint8_t)(v>>16);p[3]=(uint8_t)(v>>24);}
static uint32_t get32(const uint8_t*p){return(uint32_t)p[0]|((uint32_t)p[1]<<8)|((uint32_t)p[2]<<16)|((uint32_t)p[3]<<24);}
static uint32_t crc32(const uint8_t*p,size_t n){uint32_t c=UINT32_MAX;for(size_t i=0;i<n;i++){c^=p[i];for(unsigned b=0;b<8;b++)c=(c>>1)^((0U-(c&1U))&0xEDB88320U);}return~c;}
static uint32_t next_seq(uint32_t v){v++;return v? v:1U;}

void wifi_known_db_init(wifi_known_network_db_t *db){if(db){memset(db,0,sizeof(*db));db->next_success_sequence=1U;}}
size_t wifi_known_db_count(const wifi_known_network_db_t *db){size_t n=0;if(!db)return 0;for(size_t i=0;i<WIFI_KNOWN_NETWORK_MAX;i++)if(db->entries[i].occupied)n++;return n;}
size_t wifi_known_db_auto_count(const wifi_known_network_db_t *db){size_t n=0;if(!db)return 0;for(size_t i=0;i<WIFI_KNOWN_NETWORK_MAX;i++)if(db->entries[i].occupied&&db->entries[i].auto_connect)n++;return n;}
bool wifi_known_db_valid(const wifi_known_network_db_t *db){if(!db||db->next_success_sequence==0U)return false;for(unsigned i=0;i<WIFI_KNOWN_NETWORK_MAX;i++){const wifi_known_network_t*e=&db->entries[i];if(!e->occupied)continue;size_t sn=bounded(e->ssid,WIFI_KNOWN_SSID_MAX),pn=bounded(e->password,WIFI_KNOWN_PASSWORD_MAX);if(sn==0||sn>WIFI_KNOWN_SSID_MAX||pn>WIFI_KNOWN_PASSWORD_MAX||e->last_channel>14U||(e->has_bssid_hint&&!mac_valid(e->bssid_hint)))return false;for(unsigned j=i+1;j<WIFI_KNOWN_NETWORK_MAX;j++)if(db->entries[j].occupied&&!strcmp(e->ssid,db->entries[j].ssid))return false;}return true;}
int wifi_known_db_find(const wifi_known_network_db_t *db,const char*ssid){if(!db||!ssid)return-1;for(unsigned i=0;i<WIFI_KNOWN_NETWORK_MAX;i++)if(db->entries[i].occupied&&!strcmp(db->entries[i].ssid,ssid))return(int)i;return-1;}
static unsigned replacement(const wifi_known_network_db_t*db){for(unsigned i=0;i<WIFI_KNOWN_NETWORK_MAX;i++)if(!db->entries[i].occupied)return i;unsigned k=0;for(unsigned i=1;i<WIFI_KNOWN_NETWORK_MAX;i++)if(db->entries[i].success_sequence<db->entries[k].success_sequence)k=i;return k;}
bool wifi_known_db_upsert_success(wifi_known_network_db_t*db,const char*ssid,const char*password,uint8_t security,uint8_t channel,const uint8_t bssid[6],bool preserve_auto){if(!db||!ssid||!password)return false;size_t sn=bounded(ssid,WIFI_KNOWN_SSID_MAX),pn=bounded(password,WIFI_KNOWN_PASSWORD_MAX);if(sn==0||sn>WIFI_KNOWN_SSID_MAX||pn>WIFI_KNOWN_PASSWORD_MAX||channel>14U)return false;int found=wifi_known_db_find(db,ssid);unsigned i=found>=0?(unsigned)found:replacement(db);bool auto_value=found>=0&&preserve_auto?db->entries[i].auto_connect:false;wifi_known_network_t e={0};e.occupied=true;e.auto_connect=auto_value;e.security=security;e.last_channel=channel;e.has_bssid_hint=mac_valid(bssid);if(e.has_bssid_hint)memcpy(e.bssid_hint,bssid,6);e.success_sequence=db->next_success_sequence;db->next_success_sequence=next_seq(db->next_success_sequence);memcpy(e.ssid,ssid,sn);memcpy(e.password,password,pn);db->entries[i]=e;return true;}
bool wifi_known_db_set_auto(wifi_known_network_db_t*db,const char*ssid,bool enabled){int i=wifi_known_db_find(db,ssid);if(i<0)return false;db->entries[i].auto_connect=enabled;return true;}
bool wifi_known_db_forget(wifi_known_network_db_t*db,const char*ssid){int i=wifi_known_db_find(db,ssid);if(i<0)return false;memset(&db->entries[i],0,sizeof(db->entries[i]));return true;}
bool wifi_known_security_compatible(wifi_security_t saved,wifi_security_t visible){if(saved==WIFI_SECURITY_UNKNOWN||visible==WIFI_SECURITY_UNKNOWN)return false;if(saved==visible)return true;switch(saved){case WIFI_SECURITY_WPA_PSK:return visible==WIFI_SECURITY_WPA_WPA2_PSK;case WIFI_SECURITY_WPA_WPA2_PSK:return visible==WIFI_SECURITY_WPA2_PSK;case WIFI_SECURITY_WPA2_PSK:return visible==WIFI_SECURITY_WPA2_WPA3_PSK;case WIFI_SECURITY_WPA2_WPA3_PSK:return visible==WIFI_SECURITY_WPA3_PSK;default:return false;}}
static bool legacy_security_compatible(const wifi_known_network_t*e,wifi_security_t visible){bool legacy_psk=strlen(e->password)>0&&(e->security==WIFI_SECURITY_UNKNOWN||e->security==WIFI_SECURITY_OPEN);if(!legacy_psk)return wifi_known_security_compatible((wifi_security_t)e->security,visible);return visible==WIFI_SECURITY_WPA_PSK||visible==WIFI_SECURITY_WPA2_PSK||visible==WIFI_SECURITY_WPA_WPA2_PSK||visible==WIFI_SECURITY_WPA3_PSK||visible==WIFI_SECURITY_WPA2_WPA3_PSK;}
int wifi_known_db_select_visible(const wifi_known_network_db_t*db,const wifi_known_visible_ap_t*v,size_t n,size_t*vi){if(!db||(!v&&n)||!vi)return-1;int best=-1;size_t bv=0;for(unsigned i=0;i<WIFI_KNOWN_NETWORK_MAX;i++){const wifi_known_network_t*e=&db->entries[i];if(!e->occupied||!e->auto_connect)continue;for(size_t j=0;j<n;j++){if(!v[j].ssid||strcmp(e->ssid,v[j].ssid)||!legacy_security_compatible(e,(wifi_security_t)v[j].security))continue;if(best<0||e->success_sequence>db->entries[best].success_sequence||(e->success_sequence==db->entries[best].success_sequence&&(v[j].rssi>v[bv].rssi||(v[j].rssi==v[bv].rssi&&memcmp(v[j].bssid,v[bv].bssid,6)<0)))){best=(int)i;bv=j;}}}if(best>=0)*vi=bv;return best;}
size_t wifi_known_db_encode(const wifi_known_network_db_t*db,uint8_t*out,size_t cap){if(!wifi_known_db_valid(db)||!out||cap<WIRE_TOTAL_SIZE)return 0;memset(out,0,WIRE_TOTAL_SIZE);put32(out,WIFI_KNOWN_DB_MAGIC);out[4]=WIFI_KNOWN_DB_VERSION;out[5]=WIFI_KNOWN_NETWORK_MAX;put32(out+8,db->next_success_sequence);size_t o=WIRE_HEADER_SIZE;for(unsigned i=0;i<WIFI_KNOWN_NETWORK_MAX;i++){const wifi_known_network_t*e=&db->entries[i];size_t sn=e->occupied?strlen(e->ssid):0,pn=e->occupied?strlen(e->password):0;out[o]=(e->occupied?ENTRY_FLAG_OCCUPIED:0)|(e->auto_connect?ENTRY_FLAG_AUTO:0)|(e->has_bssid_hint?ENTRY_FLAG_BSSID:0);out[o+1]=(uint8_t)sn;out[o+2]=(uint8_t)pn;out[o+3]=e->security;out[o+4]=e->last_channel;memcpy(out+o+5,e->bssid_hint,6);put32(out+o+11,e->success_sequence);memcpy(out+o+15,e->ssid,33);memcpy(out+o+48,e->password,65);o+=WIRE_ENTRY_SIZE;}put32(out+o,crc32(out,o));return WIRE_TOTAL_SIZE;}
wifi_known_codec_status_t wifi_known_db_decode(const uint8_t*d,size_t size,wifi_known_network_db_t*db){if(!db)return WIFI_KNOWN_CODEC_CORRUPT;wifi_known_db_init(db);if(!d||size==0)return WIFI_KNOWN_CODEC_MISSING;if(size!=WIRE_TOTAL_SIZE||get32(d)!=WIFI_KNOWN_DB_MAGIC||d[4]!=WIFI_KNOWN_DB_VERSION||d[5]!=WIFI_KNOWN_NETWORK_MAX||get32(d+size-4)!=crc32(d,size-4))return WIFI_KNOWN_CODEC_CORRUPT;db->next_success_sequence=get32(d+8);size_t o=WIRE_HEADER_SIZE;for(unsigned i=0;i<WIFI_KNOWN_NETWORK_MAX;i++){uint8_t fl=d[o],sn=d[o+1],pn=d[o+2];if((fl&ENTRY_FLAG_OCCUPIED)!=0){if(sn==0||sn>WIFI_KNOWN_SSID_MAX||pn>WIFI_KNOWN_PASSWORD_MAX)return WIFI_KNOWN_CODEC_CORRUPT;wifi_known_network_t*e=&db->entries[i];e->occupied=true;e->auto_connect=(fl&ENTRY_FLAG_AUTO)!=0;e->has_bssid_hint=(fl&ENTRY_FLAG_BSSID)!=0;e->security=d[o+3];e->last_channel=d[o+4];memcpy(e->bssid_hint,d+o+5,6);e->success_sequence=get32(d+o+11);memcpy(e->ssid,d+o+15,sn);memcpy(e->password,d+o+48,pn);}o+=WIRE_ENTRY_SIZE;}if(!wifi_known_db_valid(db)){wifi_known_db_init(db);return WIFI_KNOWN_CODEC_CORRUPT;}return WIFI_KNOWN_CODEC_OK;}
