#include "wifi_connection_manager_core.h"
#include <string.h>
static bool current(wifi_conn_sm_t*s,uint32_t id){if(!s||id==0||id!=s->attempt_id){if(s)s->counters.stale_events_ignored++;return false;}return true;}
static bool phase_is(wifi_conn_sm_t*s,wifi_conn_phase_t phase){if(!s)return false;if(s->phase!=phase){s->counters.lifecycle_events_rejected++;return false;}return true;}
void wifi_conn_sm_init(wifi_conn_sm_t*s,bool enabled){if(s){memset(s,0,sizeof(*s));s->phase=WIFI_CONN_PHASE_IDLE;s->auto_enabled=enabled;}}
void wifi_conn_sm_set_auto(wifi_conn_sm_t*s,bool enabled){if(!s)return;s->auto_enabled=enabled;if(!enabled&&s->phase==WIFI_CONN_PHASE_RETRY_WAIT){s->phase=WIFI_CONN_PHASE_IDLE;s->origin=WIFI_CONN_ORIGIN_NONE;}if(enabled){s->auto_blocked_credentials=false;s->retry_count=0;}}
void wifi_conn_sm_begin(wifi_conn_sm_t*s,uint32_t id,wifi_conn_origin_t origin){if(!s||!id)return;s->attempt_id=id;s->origin=origin;s->phase=WIFI_CONN_PHASE_ASSOCIATING;s->last_failure=WIFI_CONN_FAIL_NONE;s->last_reason=0;if(origin==WIFI_CONN_ORIGIN_MANUAL){s->retry_count=0;s->auto_blocked_credentials=false;s->counters.manual_attempts++;}else s->counters.auto_attempts++;}
bool wifi_conn_sm_associated(wifi_conn_sm_t*s,uint32_t id){if(!current(s,id)||!phase_is(s,WIFI_CONN_PHASE_ASSOCIATING))return false;s->phase=WIFI_CONN_PHASE_WAITING_IP;return true;}
bool wifi_conn_sm_got_ip(wifi_conn_sm_t*s,uint32_t id){if(!current(s,id)||!phase_is(s,WIFI_CONN_PHASE_WAITING_IP))return false;s->phase=WIFI_CONN_PHASE_CONNECTED;s->retry_count=0;s->counters.successful_connections++;return true;}
bool wifi_conn_sm_failed(wifi_conn_sm_t*s,uint32_t id,wifi_conn_failure_t f,uint16_t reason,bool stable){if(!current(s,id))return false;if(s->phase!=WIFI_CONN_PHASE_ASSOCIATING&&s->phase!=WIFI_CONN_PHASE_WAITING_IP&&s->phase!=WIFI_CONN_PHASE_CONNECTED){s->counters.lifecycle_events_rejected++;return false;}s->last_failure=f;s->last_reason=reason;if(f==WIFI_CONN_FAIL_AUTH){s->counters.auth_failures++;if(s->origin==WIFI_CONN_ORIGIN_AUTO)s->auto_blocked_credentials=true;}else if(f==WIFI_CONN_FAIL_ASSOCIATION)s->counters.association_failures++;if(stable)s->counters.transient_disconnects++;if(s->origin==WIFI_CONN_ORIGIN_AUTO&&s->auto_enabled&&!s->auto_blocked_credentials&&s->retry_count<5U){s->retry_count++;s->counters.retries++;s->phase=WIFI_CONN_PHASE_RETRY_WAIT;}else{s->phase=WIFI_CONN_PHASE_IDLE;s->origin=WIFI_CONN_ORIGIN_NONE;}return true;}
bool wifi_conn_sm_timeout(wifi_conn_sm_t*s,uint32_t id){if(!current(s,id))return false;if(s->phase!=WIFI_CONN_PHASE_ASSOCIATING&&s->phase!=WIFI_CONN_PHASE_WAITING_IP){s->counters.lifecycle_events_rejected++;return false;}wifi_conn_failure_t f=s->phase==WIFI_CONN_PHASE_WAITING_IP?WIFI_CONN_FAIL_IP_TIMEOUT:WIFI_CONN_FAIL_TRANSIENT;if(f==WIFI_CONN_FAIL_IP_TIMEOUT)s->counters.ip_timeouts++;return wifi_conn_sm_failed(s,id,f,0,false);}
bool wifi_conn_sm_can_auto(const wifi_conn_sm_t*s){return s&&s->auto_enabled&&!s->auto_blocked_credentials&&s->retry_count<5U&&(s->phase==WIFI_CONN_PHASE_IDLE||s->phase==WIFI_CONN_PHASE_RETRY_WAIT);}
uint32_t wifi_conn_sm_retry_delay_ms(const wifi_conn_sm_t*s){static const uint32_t d[]={2000U,5000U,15000U,30000U,60000U};if(!s||s->retry_count==0)return 0;unsigned i=s->retry_count-1U;return d[i<5U?i:4U];}
void wifi_conn_sm_retry_started(wifi_conn_sm_t*s,uint32_t id){if(!s)return;wifi_conn_sm_begin(s,id,WIFI_CONN_ORIGIN_AUTO);}
void wifi_conn_sm_user_disconnect(wifi_conn_sm_t*s){if(!s)return;s->phase=WIFI_CONN_PHASE_IDLE;s->origin=WIFI_CONN_ORIGIN_NONE;s->last_failure=WIFI_CONN_FAIL_USER;s->retry_count=0;}
bool wifi_conn_auto_activation_due(bool allowed,wifi_conn_auto_runtime_t runtime,bool retry_due){if(!allowed)return false;return runtime==WIFI_CONN_AUTO_RUNTIME_IDLE||((runtime==WIFI_CONN_AUTO_RUNTIME_OFF||runtime==WIFI_CONN_AUTO_RUNTIME_ERROR||runtime==WIFI_CONN_AUTO_RUNTIME_RETRY_WAIT)&&retry_due);}
