name: Build firmware

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          target: esp32s3
          path: '.'
          command: idf.py build merge-bin
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ccache-esp32s3-${{ github.sha }}
          restore-keys: |
            ccache-esp32s3-

      - name: Build with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          target: esp32s3
          path: '.'
          command: idf.py build merge-bin
          extra_docker_args: >-
            -v ${{ github.workspace }}/.ccache:/root/.ccache
            -e CCACHE_DIR=/root/.ccache
            -e IDF_CCACHE_ENABLE=1

      - name: Upload merged firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware_merged
          path: build/merged-binary.bin
